### ISSUE TITLE
uniqBy has an incorrect type

### ISSUE THREAD

**Issue by user753** [mobily/ts-belt#1]
```
function uniqBy<A>(xs: ReadonlyArray<A>, uniqFn: (_1: A) => A): ReadonlyArray<A>
```
instead of 
```
function uniqBy<A, B>(xs: ReadonlyArray<A>, uniqFn: (_1: A) => B): ReadonlyArray<A>
```

**Comment by mobily** [comment]
hey @user753 👋 thanks for reporting! it's been fixed in https://github.com/mobily/ts-belt/commit/07cf8138215e4f907daa555932af7d223d36fe02 and published in `v3.0.1`
