### ISSUE TITLE
Lenses

### ISSUE THREAD

**Issue by flauwekeul** [mobily/ts-belt#15]
Hi! Great work with this library 👍 

Are there any plans for adding functions related to lenses? Such as [`lensProp`](https://ramdajs.com/docs/#lensProp) from Ramda.js?

**Comment by mobily** [comment]
hello @flauwekeul 👋 it would be nice to have lenses in `ts-belt`, but at this point, there is no plan for adding them, I would need to do some research on how to implement them properly in TS

**Comment by flauwekeul** [comment]
Do you add new functionality to ts-belt by compiling it from rescript and generating the types? I suppose that explains the performance.

**Comment by mobily** [comment]
that’s right! all functions are written in ReScript and compiled to raw JavaScript, I also use some codemods to transform generated files (see: https://github.com/mobily/ts-belt/tree/master/tools/javascript-codemods) in the pre- and post-building process
as well as I use [`genType`](https://rescript-lang.org/docs/gentype/latest/introduction) for automatically generating TS types (although, more advanced types must be added manually)

**Comment by flauwekeul** [comment]
Is adding lens functions then as easy as taking the leading lens lib in rescript and compile it to js (probably not :sweat_smile: )?

**Comment by mobily** [comment]
it's not 🙈 I did the initial research on this topic yesterday, it seems there's no type-safe and easy way to implement it in ReScript (as well as in TS), so it's unlikely it will be a part of `ts-belt` in the near future

I'm closing this issue, if you have any further questions or suggestions, please leave a comment 🚀
