### ISSUE TITLE
Curry? (feature request)

### ISSUE THREAD

**Issue by Darkle** [mobily/ts-belt#24]
Hi, I think it would be good to have a curry function in the function api if possible.

Cheers.

**Comment by mobily** [comment]
thanks for the suggestion ❤️ I will take this into consideration in the future, however, at this point, due to weak type inference in TS I’m not planning to implement currying

**Comment by leohxj** [comment]
Purify have [`curry` but no `pipe/flow`](https://gigobyte.github.io//utils/Function#export-curry. ) they said: 
> There is no such function in purify! Unfortunately it's not possible to provide a type-safe version of compose and friends, so until TypeScript allows us to do that purify will not have them.

ts-belt have `pipe/flow` but no `curry`.

Maybe purify fix the weak type in TS, Can we implement a same one?
