### ISSUE TITLE
Does the Option types support deserialization for an API?

### ISSUE THREAD

**Issue by dessalines** [mobily/ts-belt#32]
I'd like to use these Option types in an API, IE currently an interface might be:

```ts
interface Person {
  name: string;
  display_name?: string // I'd like this to be display_name: Option<string>;
  ...
}
```

Would this be supported?

**Comment by mobily** [comment]
as far as I understand this issue correctly, it is possible, since under the hood `Option<T>` is `T | null | undefined` 

feel free to reopen this issue if you need more clarification
