### ISSUE TITLE
Incorrect types D.toPairs

### ISSUE THREAD

**Issue by z81** [mobily/ts-belt#33]
![image](https://user-images.githubusercontent.com/2899598/172789176-ac19d059-8b84-42e1-bfb2-5fe47da4c040.png)

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQQDRwPLoCLoHLpjBgCmcAvnAGZQQhwDkAAiBAEbAA2AngPQwBnALRsSnGAwBQkmN1JwAKnAC8iOAG0A1iW4AuOAJhRgAOwDmAXX1ItO-YePmrcEwFcQoqBQrSAxhBNDOAATfSVVBEk4OABDazi4AEZyVCi4Nnj9ZNTo30yk8klCySJSAAo04Jy4bAA6GAgABRjgKAFq5FqQGLAysttudAA3GM5XEgsAShUAPjVeXmi4bT0DI1MzOAAfF3dPNOiFtPJJyVPJDDYAKxJfGFqSE3WSATLgya6evoHh0fGp2bzXgrezrcxpI4nADckiAA

**Comment by mobily** [comment]
thanks for posting this issue! fixed in [`v3.13.0`](https://github.com/mobily/ts-belt/releases/tag/v3.13.0)
