### ISSUE TITLE
[Feature Request] `createPipe` Creates a data-last pipe function.

### ISSUE THREAD

**Issue by nghiepit** [mobily/ts-belt#39]
Creates a data-last pipe function. First function must be always annotated. Other functions are automatically inferred.

`R.createPipe(op1, op2, op3)(data)`

```ts
createPipe(
  (x: number) => x * 2,
  (x) => x * 3
)(1) // => 6
```

**Comment by mobily** [comment]
@nghiepit `createPipe` is named `flow` in `ts-belt` and it's here → https://mobily.github.io/ts-belt/api/pipe-flow#flow :)
