### ISSUE TITLE
TypeScript doesn't use the name of the type while inferring return type

### ISSUE THREAD

**Issue by jayesh-bhoot** [mobily/ts-belt#43]
For a function

```
const toFirstName = (input: string) => R.fromPredicate(input, S.isNotEmpty, 'Enter your first name');
```

the return type is inferred as

![Screenshot from 2022-09-06 11-28-03](https://user-images.githubusercontent.com/1915507/188558223-89b6817c-0efb-41b3-b83c-48391d24d2ff.png)

which is technically true, but I would have preferred the inferred type to be the same as that of `R.fromPredicate()`

![Screenshot from 2022-09-06 11-29-40](https://user-images.githubusercontent.com/1915507/188558083-ad986359-8c02-4384-b550-ca080f90a17f.png)

Right now, I need to specify the return type explicitly as

```
const toFirstName = (input: string): Result<string, string> => R.fromPredicate(input, S.isNotEmpty, 'Enter your first name');
```

**Comment by mobily** [comment]
@jayesh-bhoot I assume that something is wrong on your side, on my end the type is inferred and narrowed correctly:

<img width="866" alt="CleanShot 2022-09-06 at 16 29 09@2x" src="https://user-images.githubusercontent.com/1467712/188661648-5e89f80b-5429-4d39-9cac-27581cce9319.png">

<img width="561" alt="CleanShot 2022-09-06 at 16 29 28@2x" src="https://user-images.githubusercontent.com/1467712/188661712-a124aa20-a13d-4152-9264-95bb79d4359d.png">

it works fine with `flow` as well:

<img width="706" alt="CleanShot 2022-09-06 at 16 31 15@2x" src="https://user-images.githubusercontent.com/1467712/188662126-70fd09f5-66bf-4497-9d67-d4d8115f92e9.png">

**Comment by jayesh-bhoot** [comment]
You are right. This problem shows up on IntelliJ WebStorm, but not on Visual Studio Code.

**Comment by jayesh-bhoot** [comment]
Tracking the issue at https://youtrack.jetbrains.com/issue/WEB-57226/Type-sometimes-isnt-inferred-correctly-The-type-hint-shows-the-structure-of-the-type-instead-of-its-name
