### ISSUE TITLE
Wrong types/behavior for A.groupBy or D.mapWithKey

### ISSUE THREAD

**Issue by Nodonisko** [mobily/ts-belt#57]
```tsx
	const someValues = [ { id: 1, value: "hello" }, { id: 2, value: "world" } ]
    pipe(
        someValues,
        A.groupBy(value => value.id),
        D.mapWithKey((id, values) => {
			console.log(typeof id) // prints out string
			const numId: number = id; // this should throw, but it doesn't because type is number instead of string

			return values;
        }),
    );
```

This is kind of interesting problem it could be either type issue or implementation issue. First solution could be that it will be same type as `value.id` (`A.groupBy(value => value.id)`) and only types that could become object keys should be allowed (probably only number/string ?). Then implementation needs to be fixed.

 Or if current implementation is correct it should be types as always `string`.

**Comment by mobily** [comment]
@Nodonisko this is fixed in `v4.0.0-rc.0` (the latest is `v4.0.0-rc.1`)

<img width="1293" alt="CleanShot 2022-12-04 at 18 37 56@2x" src="https://user-images.githubusercontent.com/1467712/205506389-00aca39b-e92f-4dd7-ac66-bd4ab738b309.png">

**Comment by ivan-kleshnin** [comment]
I also have problems with `A.groupBy` due to the way it's typed:

```ts
import {A, D, pipe} from "@mobily/ts-belt"

function groupErrors(errors: Dict<string>): Dict<string[]> {
  return pipe(
    errors,
    D.toPairs,
    A.groupBy(pair => pair[1]), 
    D.map((pairs: any): string[] => // <-- remove this `any` suppressor to see an issue
      A.map(pairs, (pair: [string, string]) => pair[0])
    )
  )
}

console.log(groupErrors({
  login1: "NotFoundError",
  login2: "NotFoundError",
  login3: "TimeoutError",
  login4: "TimeoutError",
}))

// ->
const result = {
  NotFoundError: ["login1", "login2"],
  TimeoutError: ["login3", "login4"]
}
void result
```

![Screen Shot 2023-01-10 at 13 46 49](https://user-images.githubusercontent.com/2128182/211531471-62695f8f-3054-48b9-86a4-5301b5411cf0.png)

**Comment by Nodonisko** [comment]
You can probably wrap pairs in `F.toMutable` to solve issue, but I agree with you that `readonly` are very problematic. I already created this issue about them #65
