### ISSUE TITLE
Use as Rescript package?

### ISSUE THREAD

**Issue by jaredramirez** [mobily/ts-belt#66]
Hey there, this project looks really cool!

Is it possible to use this as a regular Rescript package? It looks like the NPM package only published the generated ts/js files. Is there any future version where this is supported?

**Comment by mobily** [comment]
@jaredramirez I'm not sure about that, I have never even taken that under consideration, it would probably require a few adjustments (and even more time for code maintenance), if you had time then I'd be grateful for checking if ts-belt works in ReScript too :) 

edit: for now I'm closing the issue, feel free to reopen it if you need some help while working on a ReScript version :)
