### ISSUE TITLE
Support Set operations

### ISSUE THREAD

**Issue by ivan-kleshnin** [mobily/ts-belt#69]
Hi! Do you have plans to support `Set` operations in this library? Maybe in future? Builtin `Set` is even more limited than `Array` so it would defenitely benefit from additional helpers. No other comparable library does it so far, AFAIK.

Letter `S` is already taken though 😅:

```ts
const E = {
  intersection<T>(setA: Set<T>, setB: Set<T>): Set<T> {
    return new Set([...setA].filter(element => setB.has(element)))
  },

  difference<T>(setA: Set<T>, setB: Set<T>): Set<T> {
    return new Set([...setA].filter(element => !setB.has(element)))
  },
}

E.intersection(new Set(["foo", "bar"]), new Set(["bar", "spam"]))
// => new Set(["bar"])

E.difference(new Set(["foo", "bar"]), new Set(["bar", "spam"]))
// => new Set(["foo"])
```

**Comment by mobily** [comment]
@ivan-kleshnin unfortunately no, I don't consider adding `Set` helpers at the moment, sorry!
