### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by lumosminima** [mobily/ts-belt#92]
Never used a functional utility library before and after researching a bit this one claims to be the fastest and better on library marketing material yet the last commit is almost a year ago and issues aren't being worked on. I see that there is also a v4 which isn't merged yet so is this going to be maintained in future? Is production ready? If not then can someone point me to the next best option? Thank You.

**Comment by mobily** [comment]
@lumosminima hey there! 👋 please read: https://github.com/mobily/ts-belt/issues/93
